_insar_arm_clean_paths
unset -f use_alosStack use_topsStack use_stripmapStack use_mintpy _insar_arm_use_stack _insar_arm_clean_paths
unset _INSAR_ARM_ROOT
if [ "${_INSAR_ARM_HAD_ISCE_HOME-}" = yes ]; then export ISCE_HOME="${_INSAR_ARM_PREV_ISCE_HOME}"; else unset ISCE_HOME; fi
if [ "${_INSAR_ARM_HAD_ISCE_STACK-}" = yes ]; then export ISCE_STACK="${_INSAR_ARM_PREV_ISCE_STACK}"; else unset ISCE_STACK; fi
if [ "${_INSAR_ARM_HAD_PYTHONPATH-}" = yes ]; then export PYTHONPATH="${_INSAR_ARM_PREV_PYTHONPATH}"; else unset PYTHONPATH; fi
if [ "${_INSAR_ARM_HAD_PYTHONHOME-}" = yes ]; then export PYTHONHOME="${_INSAR_ARM_PREV_PYTHONHOME}"; else unset PYTHONHOME; fi
if [ "${_INSAR_ARM_HAD_CONDA_SUBDIR-}" = yes ]; then export CONDA_SUBDIR="${_INSAR_ARM_PREV_CONDA_SUBDIR}"; else unset CONDA_SUBDIR; fi
if [ "${_INSAR_ARM_HAD_MAGICK_CONFIGURE_PATH-}" = yes ]; then export MAGICK_CONFIGURE_PATH="${_INSAR_ARM_PREV_MAGICK_CONFIGURE_PATH}"; else unset MAGICK_CONFIGURE_PATH; fi
unset _INSAR_ARM_HAD_ISCE_HOME _INSAR_ARM_PREV_ISCE_HOME _INSAR_ARM_HAD_ISCE_STACK _INSAR_ARM_PREV_ISCE_STACK
unset _INSAR_ARM_HAD_PYTHONPATH _INSAR_ARM_PREV_PYTHONPATH _INSAR_ARM_HAD_PYTHONHOME _INSAR_ARM_PREV_PYTHONHOME
unset _INSAR_ARM_HAD_CONDA_SUBDIR _INSAR_ARM_PREV_CONDA_SUBDIR _INSAR_ARM_HAD_MAGICK_CONFIGURE_PATH _INSAR_ARM_PREV_MAGICK_CONFIGURE_PATH
