package:
  name: isce2
  version: 2.6.5
source:
  fn: isce2-2.6.5.tar.gz
  url: https://codeload.github.com/isce-framework/isce2/tar.gz/b7702cfbd571681a133ebc5c3b23a10c78d52706
  sha256: 2d9cea6c200c19977e2ad725de7857edc698b10d2b9f60007d7e3d4a0ff9edda
build:
  number: 1
  skip: true  # [not osx or not arm64 or py != 312]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib('c') }}
    - cmake >=3.18,<4
    - ninja
    - pkg-config
  host:
    - xorg-xorgproto
    - xorg-xbitmaps
    - python
    - numpy 1.26.*
    - cython <3
    - fftw
    - libgdal-core 3.10.*
    - hdf5
    - libopencv 4.11.*
    - llvm-openmp
    - insar-arm-motif 2.3.8
    - xorg-libx11
    - xorg-libxt
    - xorg-libxft
  run:
    - python
    - numpy >=1.26,<2
    - scipy <1.16
    - h5py
    - gdal 3.10.*
    - scikit-image
    - requests
    - matplotlib-base
    - insar-arm-motif 2.3.8
    - xorg-libxt
    - xorg-libxft
    - llvm-openmp
test:
  imports:
    - isce
  commands:
    - test -x "$PREFIX/bin/mdx"
    - test -f "$PREFIX/share/isce2/alosStack/create_cmds.py"
about:
  home: https://github.com/isce-framework/isce2
  license: Apache-2.0 AND LicenseRef-ISCE2-Third-Party
  license_file:
    - LICENSE
    - LICENSE-2.0.txt
    - contrib/Snaphu/include/snaphu_cs2types.h
  summary: Experimental native Apple Silicon ISCE2 package with all three Stack processors
